#!/bin/sh
### BEGIN INIT INFO
# Provides:          infrastructure
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: rook_test_infrastructure
# Description:       provides infrastructure for testing rook
### END INIT INFO




case "$1" in
 start)
    export HOME=/home/root
    export DEBIAN_FRONTEND=noninteractive
    export LC_ALL=C
    docker info #--> need better way to determine docker is ready

    #Docker import the image there, with ci:latest or something
    docker load < $(find /from-host/ -type f -name *.tar)

    #Git download test repo --> templates, rook-*.yamls, controller.yaml
    git clone https://github.com/dangula/rookStartUpScripts.git

    cd rookStartUpScripts/

    chmod +x rook-dind-cluster-v1.5.sh

 #   sleep 15

    #./rook-dind-cluster-v1.5.sh up

    #untaint
    #kubectl taint nodes --all dedicated-

 #   sleep 5

#add drain
#kubectl drain kube-node-2 --force --ignore-daemonsets

#kubectl delete node kube-node-2 --force


#WAIT --> add real wait code here
 #   sleep 20

     #PATCH KUBE-CONTROLLER-MANAGER
  #   yes | cp -rf kube-controller-manager.json $(find /var/lib/docker/aufs/mnt -type f -name kube-controller-manager.json)


   # sleep 5

#TODO --> update rook operator with image pull location and tag

#INSTALL CEPH IN ALL NODES
#curl --unix-socket /var/run/docker.sock http:/containers/json | jq -r '.[].Id' | xargs -i docker exec -i {} bash -c 'apt-get -y update && apt-get install -qqy ceph-common'


#    kubectl create -f rook/rook-operator.yaml

#WAIT --> add real wait code here
    #sleep 30

    #kubectl create -f rook/rook-cluster.yaml

#WAIT --> add real wait code here
    #sleep 100

#kubectl create -f rook/rook-pool.yaml
    #sleep 10


    echo Rook Test infrastructure setup is complete!!!
;;
 stop)

   ;;
 restart)
  ./dind-cluster-v1.5.sh down
  sleep 5

   sleep 1
   ;;
 *)
   echo "Usage: rook_test_infrastructure {start|stop|restart}" >&2
   exit 3
   ;;
esac



